### ISSUE TITLE
Error: 'Viewport' is imported from both 'package:flame/src/game/viewport.dart' and 'package:flame_forge2d/viewport.dart'.

### ISSUE THREAD

**Issue by gustav0** [flame-engine/forge2d#19]
Hi, I just started using forge2d and I can't manage to get it running. This literally happens on an empty project. My code is just:

```
// main.dart
void main() {
  runApp(GameWidget(game: MyGame()));
}
```

```
// game.dart
class MyGame extends Forge2DGame {} // This works if I use flame's BaseGame instead.
```

My dependencies look like this:
```
// pubspec.yaml

dependencies:
  # other stuff
  flame: ^1.0.0-rc7  # tried removing this
  forge2d: ^0.6.5  # tried removing this
  flame_forge2d: ^0.6.4-rc4
```

I'm kinda new to dart/flutter, so I actually have no idea what's the todo here.
