### ISSUE TITLE
New version Please

### ISSUE THREAD

**Issue by madhav2348** [flame-engine/forge2d#94]
The current Dart SDK version is 3.4.0.

Because forge2d doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

**Comment by spydon** [comment]
< 3.0.0 confusingly means < 4.0.0 in pub, so it does support sound null safety.

**Comment by spydon** [comment]
And I just checked our constraints, they are already updated:
```
  sdk: ">=3.0.0 <4.0.0"
```

**Comment by madhav2348** [comment]
first when i just adding the dependencies through terminal 
it was giving :
The current Dart SDK version is 3.4.0.

Because forge2d doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

and then I was just adjusting and changing the version of SDK  and forge2d , thinking somehow it will work , but it didnt

so later I just write the dependencies directly in yaml file
and then when i did this :

 sdk: '>=3.4.0 <4.0.0'

and 

flame_forge2d: ^0.18.0

 result :
Because forge2d depends on flame_forge2d ^0.18.0 which depends on forge2d ^0.13.0, forge2d ^0.13.0 is required.
So, because forge2d is 0.1.0, version solving failed.

**Comment by spydon** [comment]
Post your full `pubspec.yaml` file please.

**Comment by madhav2348** [comment]
name: forge2d
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  characters: ^1.3.0
  flame: ^1.17.0
  flame_forge2d: ^0.18.0


  flame_kenney_xml: ^0.1.0
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images
``

**Comment by madhav2348** [comment]
```  
name: forge2d
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  characters: ^1.3.0
  flame: ^1.17.0
  flame_forge2d: ^0.18.0


  flame_kenney_xml: ^0.1.0
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images

```
